enableGlobalCache: true

pnpEnableEsmLoader: true

globalFolder: ../.yarn/berry

packageExtensions:
  '@mikro-orm/postgresql@*':
    dependencies:
      '@mikro-orm/core': '*'

yarnPath: .yarn/releases/yarn-remote.cjs
